### ISSUE TITLE
please, HOW TO DELETE MORE THAN ONE FILE IN ONE COMMIT AAAAAAAA

### ISSUE THREAD

**Issue by NamorNiradnug** [korochun/Medieval-Rise#1]
please, delete files .wpr, .wpu, __pycache__, MainWindow.py and GameMenu.py from / (not from graphics), and help meeeee

**Comment by korochun** [comment]
Add these files to .gitignore

**Comment by korochun** [comment]
And don't open issues for that, please.

**Comment by NamorNiradnug** [comment]
thank you!
